M48
; DRILL file {KiCad 9.0.5} date 2025-10-14T15:47:51-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-14T15:47:51-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.200
%
G90
G05
T1
X-3.91Y-19.24
X1.87Y-19.24
X7.99Y-19.24
X13.77Y-19.24
T2
X-21.82Y14.22
X-21.82Y11.92
T3
X-19.0Y5.93
X-19.0Y-2.07
M30
