M48
; DRILL file KiCad 10.0.1 date 2026-05-08T09:13:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-08T09:13:43-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.200
%
G90
G05
T1
X-3.91Y-19.24
X1.87Y-19.24
X7.99Y-19.24
X13.77Y-19.24
T2
X-21.82Y14.22
X-21.82Y11.92
T3
X-19.0Y5.93
X-19.0Y-2.07
M30
